services:
  - type: web
    name: mock-test-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: DATABASE_CHANNEL_ID
        sync: false
      - key: DEBUG
        value: "False"
      - key: LOG_LEVEL
        value: "INFO"
